import Head from 'next/head';
import { Fragment } from 'react';
import Chat from '../Components/Chat/Chat';
import Sidebar from '../Components/Sidebar';

import classes from '../styles/Home.module.css';

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Chatty Fatty</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='icon'
          href='https://play-lh.googleusercontent.com/cF_oWC9Io_I9smEBhjhUHkOO6vX5wMbZJgFpGny4MkMMtz25iIJEh2wASdbbEN7jseAx'
        />
      </Head>

      <div className={classes.main}>
        <div className={classes.main_box}>
          <Sidebar />
          <Chat />
        </div>
      </div>
    </Fragment>
  );
}
